### ISSUE TITLE
Model Loading

### ISSUE THREAD

**Issue by SRL94** [UKPLab/coling2018-graph-neural-networks-question-answering#10]
Hi,
I run `python -m questionanswering.evaluate_on_test trainedmodels/DS_COLING_2018_QA_models/OneEdgeModel_2018-03-14_194679.pkl configs/webqsp_eval_config.yaml` and the script says: 

> Loading model from file: None

I also try on other models, and I got the same issue.

**Comment by daniilsorokin** [comment]
Oh, sorry this is just a small logging bug. It should be working nonetheless. Does evaluate or stop after that? Did you manage to set up Wikidata endpoint successfully?

**Comment by SRL94** [comment]
Thank you for the swift reply! I haven't successfully set up Wikidata endpoint. Some error occurs and I am trying to solve it.
