### ISSUE TITLE
WebQSP-WD dataset request

### ISSUE THREAD

**Issue by svakulenk0** [UKPLab/coling2018-graph-neural-networks-question-answering#3]
Hi Daniil

Can you please share your version of the WebQuestions dataset for WikiData i.e. WebQSP-WD, which you used for evaluation ?

Regards
Svitlana

**Comment by daniilsorokin** [comment]
Hi!

Added info on the data set. Please take a look and let me know if you need anything else.

**Comment by svakulenk0** [comment]
"Not found" for https://github.com/UKPLab/coling2018-graph-neural-networks-question-answering/WebQSP_WD_v1.zip

**Comment by daniilsorokin** [comment]
Oh, stupid typo. It should be 
https://public.ukp.informatik.tu-darmstadt.de/coling2018-graph-neural-networks-question-answering/WebQSP_WD_v1.zip

Will fix in a second in the readme.

**Comment by svakulenk0** [comment]
All good! Thanks for sharing 👍
