### ISSUE TITLE
Download the pre-trained models

### ISSUE THREAD

**Issue by yang840808206** [UKPLab/coling2018-graph-neural-networks-question-answering#4]
Hi,

Could you please  tell me how to download a trained model?Also, could you please tell me the format of your training ggnn data? 

Thanks

**Comment by daniilsorokin** [comment]
Here are the models: 
https://public.ukp.informatik.tu-darmstadt.de/coling2018-graph-neural-networks-question-answering/DS_COLING_2018_QA_models.zip
Some info on the training data format is here:
https://github.com/UKPLab/coling2018-graph-neural-networks-question-answering/blob/master/WEBQSP_WD_README.md#reading-in-the-data
I will try to update it with an example soon.
