### ISSUE TITLE
Using the pre-trained model get error

### ISSUE THREAD

**Issue by Mystery-000** [UKPLab/coling2018-graph-neural-networks-question-answering#6]
Hi，when I Run python -m questionanswering.evaluate_on_test [model_file_path] configs/webqsp_eval_config.yaml [random_seed] [GPU_id] command，get the exception error：Exception: Check whether you have started the CoreNLP server e.g.
$ cd stanford-corenlp-full-2015-12-09/ 
$ java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer
However，I have had started the nlp server，eg:[main] INFO CoreNLP - Starting server...
[main] INFO CoreNLP - StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9000
Could help me solve this problem？
Thank you for your attention~

**Comment by daniilsorokin** [comment]
Hi,

yes, you need a running instance of the Stanford CoreNLP server (https://stanfordnlp.github.io/CoreNLP/corenlp-server.html) for tokenisation and NE recognition. 

Best,
Daniil

**Comment by SRL94** [comment]
Hi Daniil,

I have the same issue. I have started the nlp server and run the code again, but I still got the same issue: Exception: Check whether you have started the CoreNLP server.

Best,
SR

**Comment by SRL94** [comment]
Also, can I know what version of CoreNLP did you use in your project? Thank you for your help.

**Comment by SRL94** [comment]
> Hi Daniil,
> 
> I have the same issue. I have started the nlp server and run the code again, but I still got the same issue: Exception: Check whether you have started the CoreNLP server.
> 
> Best,
> SR

I replace `corenlp = StanfordCoreNLP('http://semanticparsing:9000')` by` corenlp = StanfordCoreNLP('http://localhost:9000')`. The CoreNLP connection issue is solved, but I get a new
exception:  

> properties={**corenlp_properties, **corenlp_caseless} if caseless else corenlp_properties
> AttributeError: 'str' object has no attribute 'get'

I guess it is because of CoreNLP version. I am using 

> stanford-corenlp-full-2018-10-05

>

**Comment by hsaghir** [comment]
@SRL94 you need to also download CoreNLP models for your specific language from here: https://stanfordnlp.github.io/CoreNLP/#human-languages-supported

**Comment by daniilsorokin** [comment]
Yes, exactly, do not forget the CoreNLP models as well. Thanks, @hsaghir!
