### ISSUE TITLE
Wikidata and fackel installation

### ISSUE THREAD

**Issue by SRL94** [UKPLab/coling2018-graph-neural-networks-question-answering#7]
Hi,
How can I install fackel and wikidata after downloading them?

**Comment by SRL94** [comment]
I solve it by:
python setup.py install

**Comment by daniilsorokin** [comment]
Hi,

yes, or navigate to the fackel or wikidata folder and run `pip install .`
Or simply put them into the question-answering project folder. 

Best wishes
Daniil
