### ISSUE TITLE
Wikidata How To

### ISSUE THREAD

**Issue by SRL94** [UKPLab/coling2018-graph-neural-networks-question-answering#8]
Hi,

I have downloaded wdtk-client-0.8.0.jar from [github](https://github.com/Wikidata/Wikidata-Toolkit/releases/tag/v0.8.0), but I did not find the "rdf_dumps.ini" file to run` java -jar wdtk-client-0.8.0-SNAPSHOT.jar --config rdf_dumps.ini` Could you please share the config file? @daniilsorokin

**Comment by abmitra84** [comment]
> Hi,
> 
> I have downloaded wdtk-client-0.8.0.jar from [github](https://github.com/Wikidata/Wikidata-Toolkit/releases/tag/v0.8.0), but I did not find the "rdf_dumps.ini" file to run` java -jar wdtk-client-0.8.0-SNAPSHOT.jar --config rdf_dumps.ini` Could you please share the config file?

I am having the same issue, kindly provide the .ini file

**Comment by daniilsorokin** [comment]
Uploaded: https://github.com/UKPLab/coling2018-graph-neural-networks-question-answering/blob/master/rdf_dumps.ini
