### ISSUE TITLE
virtuoso

### ISSUE THREAD

**Issue by SRL94** [UKPLab/coling2018-graph-neural-networks-question-answering#9]
Hi,

I download virtuoso from [link](https://sourceforge.net/projects/virtuoso/files/virtuoso/7.2.4.2/), but I did not find a "var" folder in "virtuoso-opensource-7.2.4" folder. Should I create the "var" folder on my own? Or this is something wrong with my installation?

**Comment by daniilsorokin** [comment]
Yes, try to create it yourself. Generally, you can put the database files anywhere, you would just need to change all the paths in the virtuoso.ini file.

**Comment by SRL94** [comment]
Thank you @daniilsorokin !
